version: '2.0'
services:
  redis:
    image: redis:alpine
    container_name: sandbox-redis

  mariadb:
    image: mariadb:10.1
    container_name: sandbox-mariadb
    working_dir: /application
    command: [mysqld, --character-set-server=utf8mb4, --collation-server=utf8mb4_unicode_ci]
    volumes:
      - .:/application
      - pimcore-database:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=ROOT
      - MYSQL_DATABASE=pimcore
      - MYSQL_USER=pimcore
      - MYSQL_PASSWORD=pimcore

  webserver:
    image: httpd
    container_name: sandbox-webserver
    working_dir: /application
    volumes:
        - .:/application
        - ./.docker/apache/httpd.conf:/usr/local/apache2/conf/httpd.conf
        - ./.docker/apache/pimcore.conf:/usr/local/apache2/conf/sites-enabled/100-pimcore.conf
    ports:
     - "2000:80"
    links:
      - php-fpm:php-fpm

  php-fpm:
    build: .docker/php-fpm7.0
    container_name: sandbox-php-fpm
    working_dir: /application
    volumes:
      - .:/application:cached
      - ./.docker/php-fpm7.0/php-ini-overrides.ini:/etc/php/7.0/cli/conf.d/99-overrides.ini
    links:
     - mariadb:mariadb
     - redis:redis

volumes:
  pimcore-database: